services:
  db:
    image: mariadb:11 
    container_name: mariadb-db
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:  
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${DB_USER} -p${DB_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  api:
    image: danielmchachagua/club-norte-back:0.0.21
    container_name: club-norte
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db-data:



# services:
#   db:
#     image: mariadb:11 
#     container_name: mariadb-db
#     ports:
#       - "3307:3306"
#     env_file:
#       - .env
#     environment:
#       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#       - MYSQL_DATABASE=${MYSQL_DATABASE}
#     volumes:
#       - db-data:/var/lib/mysql
#     healthcheck:  
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASSWORD}"]
#       interval: 10s
#       timeout: 5s
#       retries: 10
#     restart: unless-stopped


#   api:
#     image: danielmchachagua/club-norte-back:0.0.2
#     container_name: club-norte
#     ports:
#       - "3000:3000"
#     env_file:
#       - .env
#     depends_on:
#       - db
#     restart: unless-stopped


# volumes:
#   db-data:
