services:
  db:
    image: mariadb:11 
    container_name: mariadb-db
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:  
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    image: danielmchachagua/club-norte-back:0.0.2
    container_name: club-norte
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - /home/daniel/go/bin/swag:/home/daniel/go/bin/
    depends_on:
      - db

volumes:
  db-data:
